# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWiluxfwoNHJUHQ6mFtxfUnMKrMJuA6W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

import os

print(os.getcwd())
print(os.listdir())

from google.colab import files

uploaded = files.upload()

import pandas as pd

customers = pd.read_csv("DimCustomer.csv")
dates = pd.read_csv("DimDate.csv")
geography = pd.read_csv("DimGeography.csv")
orders = pd.read_csv("DimOrder.csv")
products = pd.read_csv("DimProduct.csv")

customers = pd.read_csv("DimCustomer.csv")
dates = pd.read_csv("DimDate.csv")
geography = pd.read_csv("DimGeography.csv")
orders = pd.read_csv("DimOrder.csv")
products = pd.read_csv("DimProduct.csv")
sales = pd.read_csv("FactSales.csv")

tables = {
    "Customers": customers,
    "Dates": dates,
    "Geography": geography,
    "Orders": orders,
    "Products": products,
    "Sales": sales
}

for name, df in tables.items():
    print(f"{name}: {df.shape}")

sales.head()

orders.head()

customers.head()

products.head()

dates.head()

geography.head()

for name, df in tables.items():
    print("\n", "="*50)
    print(name)
    print("="*50)
    print(df.dtypes)

for name, df in tables.items():
    print("\n", name)
    print(df.isnull().sum())

for name, df in tables.items():
    print(name, "duplicates:", df.duplicated().sum())

print("Duplicate Customer IDs:",
      customers["Customer_ID"].duplicated().sum())

print("Duplicate Product IDs:",
      products["Product_ID"].duplicated().sum())

print("Duplicate Order IDs:",
      orders["Order_ID"].duplicated().sum())

missing_customers = orders[
    ~orders["Customer_ID"].isin(customers["Customer_ID"])
]

print(len(missing_customers))

missing_products = sales[
    ~sales["Product_ID"].isin(products["Product_ID"])
]

print(len(missing_products))

missing_orders = sales[
    ~sales["Order_ID"].isin(orders["Order_ID"])
]

print(len(missing_orders))

print(sales.columns.tolist())

sales["Calculated_Sales"] = (
    sales["Quantity"]
    * sales["Unit_Price"]
    * (1 - sales["Discount_Pct"])
)

sales["Sales_Difference"] = (
    sales["Sales"] - sales["Calculated_Sales"]
)

sales["Sales_Difference"].describe()

sales["Calculated_Profit"] = (
    sales["Sales"] - sales["Cost"]
)

sales["Profit_Difference"] = (
    sales["Profit"] - sales["Calculated_Profit"]
)

customers_clean = customers.copy()
dates_clean = dates.copy()
geography_clean = geography.copy()
orders_clean = orders.copy()
products_clean = products.copy()
sales_clean = sales.copy()

customers_clean["Signup_Date"] = pd.to_datetime(
    customers_clean["Signup_Date"],
    errors="coerce"
)

orders_clean["Order_Date"] = pd.to_datetime(
    orders_clean["Order_Date"],
    errors="coerce"
)

dates_clean["Date"] = pd.to_datetime(
    dates_clean["Date"],
    errors="coerce"
)

print(customers_clean.dtypes)
print(orders_clean.dtypes)
print(dates_clean.dtypes)

for name, df in {
    "Customers": customers_clean,
    "Orders": orders_clean,
    "Products": products_clean,
    "Geography": geography_clean,
    "Sales": sales_clean
}.items():

    print("\n", name)
    print(df.isnull().sum())

for name, df in {
    "Customers": customers_clean,
    "Orders": orders_clean,
    "Products": products_clean,
    "Geography": geography_clean,
    "Sales": sales_clean
}.items():

    print(name, df.duplicated().sum())

customers_clean["Customer_ID"].duplicated().sum()

sales_clean[
    sales_clean["Quantity"] <= 0
]

sales_clean = sales_clean[
    sales_clean["Quantity"] > 0
].copy()

sales_clean[
    sales_clean["Unit_Cost"] <= 0
]

sales_clean[
    sales_clean["Unit_Price"] <= 0
]

sales_clean[
    (sales_clean["Discount_Pct"] < 0) |
    (sales_clean["Discount_Pct"] > 1)
]

sales_clean["Expected_Sales"] = (
    sales_clean["Quantity"]
    * sales_clean["Unit_Price"]
    * (1 - sales_clean["Discount_Pct"])
)

sales_clean["Sales_Difference"] = (
    sales_clean["Sales"]
    - sales_clean["Expected_Sales"]
)

sales_clean["Sales_Difference"].abs().max()

sales_clean["Expected_Profit"] = (
    sales_clean["Sales"]
    - sales_clean["Cost"]
)

sales_clean["Profit_Difference"] = (
    sales_clean["Profit"]
    - sales_clean["Expected_Profit"]
)

sales_clean["Profit_Difference"].abs().max()

print(products_clean["Category"].unique())

print(products_clean["Subcategory"].unique())

print(products_clean["Subcategory"].unique())

print(orders_clean["Sales_Channel"].unique())
print(orders_clean["Payment_Method"].unique())
print(orders_clean["Order_Status"].unique())

orders_clean["Sales_Channel"] = (
    orders_clean["Sales_Channel"]
    .str.strip()
    .str.title()
)

invalid_customers = orders_clean[
    ~orders_clean["Customer_ID"].isin(
        customers_clean["Customer_ID"]
    )
]

print("Invalid Customer IDs:", len(invalid_customers))

invalid_orders = sales_clean[
    ~sales_clean["Order_ID"].isin(
        orders_clean["Order_ID"]
    )
]

print("Invalid Order IDs:", len(invalid_orders))

invalid_products = sales_clean[
    ~sales_clean["Product_ID"].isin(
        products_clean["Product_ID"]
    )
]

print("Invalid Product IDs:", len(invalid_products))

sales_clean["Sales"].describe()

Q1 = sales_clean["Sales"].quantile(0.25)
Q3 = sales_clean["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = sales_clean[
    (sales_clean["Sales"] < lower) |
    (sales_clean["Sales"] > upper)
]

print("Outliers:", len(outliers))

cleaning_report = pd.DataFrame({
    "Check": [
        "Missing Values",
        "Duplicate Rows",
        "Duplicate Customer IDs",
        "Duplicate Product IDs",
        "Duplicate Order IDs",
        "Invalid Quantity",
        "Invalid Discount",
        "Invalid Customer References",
        "Invalid Product References",
        "Invalid Order References"
    ],
    "Status": [
        "Checked",
        "Checked",
        "Checked",
        "Checked",
        "Checked",
        "Checked",
        "Checked",
        "Checked",
        "Checked",
        "Checked"
    ]
})

cleaning_report
